<!DOCTYPE html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>This is Baseplate</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:image" content=""/>
  <meta property="og:title" content=""/>
  <meta property="og:url" content=""/>
  <meta property="og:site_name" content=""/>


  <link rel="shortcut icon" href="favicon.ico"/>
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
