<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Gulp! Web App Workflow</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:image" content="http://rmdias.com/gulpworkflow/img/gulp-logo.png"/>
  <meta property="og:title" content="Gulp Web App Workflow - Boilerplate from web app using Gulp.JS"/>
  <meta property="og:url" content="http://rmdias.com/gulpworkflow"/>
  <meta property="og:site_name" content="Gulp Web App Workflow"/>


  <link rel="shortcut icon" href="./favicon.ico"/>
  <link rel="stylesheet" href="./css/style.min.css">
  <script src="./js/vendor/modernizr-2.7.1.min.js"></script>
</head>
<body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- Add your site or application content here -->